package com.github.microwww.redis.protocal.operation;

import com.github.microwww.redis.RequestParams;
import com.github.microwww.redis.database.GeoData;
import com.github.microwww.redis.database.HashKey;
import com.github.microwww.redis.database.Member;
import com.github.microwww.redis.database.RedisDatabase;
import com.github.microwww.redis.database.SortedSetData;
import com.github.microwww.redis.protocal.AbstractOperation;
import com.github.microwww.redis.protocal.RedisOutputProtocol;
import com.github.microwww.redis.protocal.RedisRequest;
import com.github.microwww.redis.util.GeoHashUtil;

import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Geospatial commands. Generated by Cursor. Version: 0.3.4.
 */
public class GeoOperation extends AbstractOperation {

    private static final String WRONGTYPE_ERR = "WRONGTYPE Operation against a key holding the wrong kind of value";
    /** Only add when member does not exist. */
    private static final String OPT_ONLY_IF_NOT_EXISTS = "NX";
    /** Only update when member already exists. */
    private static final String OPT_ONLY_IF_EXISTS = "XX";
    /** Return count of added + updated (otherwise return only added count). */
    private static final String OPT_WITH_CHANGED_COUNT = "CH";
    private static final String OPT_WITHDIST = "WITHDIST";
    private static final String OPT_WITHHASH = "WITHHASH";
    private static final String OPT_WITHCOORD = "WITHCOORD";
    private static final String OPT_COUNT = "COUNT";
    private static final String OPT_ASC = "ASC";
    private static final String OPT_DESC = "DESC";
    private static final String OPT_STORE = "STORE";
    private static final String OPT_STOREDIST = "STOREDIST";
    private static final String DEFAULT_UNIT = "m";

    // -------------------------------------------------------------------------
    // GEOADD key [NX|XX] [CH] longitude latitude member [longitude latitude member ...]
    // -------------------------------------------------------------------------
    public void geoadd(RedisRequest request) throws IOException {
        request.expectArgumentsCountGE(4);
        RequestParams[] args = request.getParams();
        int i = 0;
        HashKey key = args[i++].byteArray2hashKey();
        boolean nx = false, xx = false, ch = false;
        while (i < 4) {
            String opt = args[i].getByteArray2string().toUpperCase();
            if (OPT_ONLY_IF_NOT_EXISTS.equals(opt)) {
                nx = true;
                i++;
            } else if (OPT_ONLY_IF_EXISTS.equals(opt)) {
                xx = true;
                i++;
            } else if (OPT_WITH_CHANGED_COUNT.equals(opt)) {
                ch = true;
                i++;
            } else {
                break;
            }
        }
        if (nx && xx) {
            throw new IllegalArgumentException("NX and XX options are mutually exclusive");
        }
        GeoData data = getOrCreateGeoData(request, key);
        if (data == null) return;
        final boolean addNx = nx, addXx = xx, addCh = ch;
        int totalAdded = 0, totalChanged = 0;
        while (i + 2 < args.length) {
            double lon = args[i++].byteArray2decimal().doubleValue();
            double lat = args[i++].byteArray2decimal().doubleValue();
            byte[] member = args[i++].getByteArray();
            int[] res = data.sync(() -> data.add(addNx, addXx, addCh, lon, lat, member));
            totalAdded += res[0];
            if (addCh && res.length > 1) totalChanged += res[1];
        }
        RedisOutputProtocol out = request.getOutputProtocol();
        out.writer(addCh ? totalAdded + totalChanged : totalAdded);
    }

    // -------------------------------------------------------------------------
    // GEODIST key member1 member2 [m|km|ft|mi]
    // -------------------------------------------------------------------------
    public void geodist(RedisRequest request) throws IOException {
        request.expectArgumentsCountGE(3);
        RequestParams[] args = request.getParams();
        HashKey key = args[0].byteArray2hashKey();
        String unit = args.length > 3 ? args[3].getByteArray2string() : DEFAULT_UNIT;
        Optional<GeoData> opt = request.getDatabase().get(key, GeoData.class);
        Optional<Double> dist = opt.flatMap(g -> g.distance(args[1].byteArray2hashKey(), args[2].byteArray2hashKey(), unit));
        RedisOutputProtocol out = request.getOutputProtocol();
        if (dist.isPresent()) {
            out.writer(String.valueOf(dist.get()).getBytes(StandardCharsets.UTF_8));
        } else {
            out.writerNull();
        }
    }

    // -------------------------------------------------------------------------
    // GEOHASH key member [member ...]
    // -------------------------------------------------------------------------
    public void geohash(RedisRequest request) throws IOException {
        request.expectArgumentsCountGE(2);
        RequestParams[] args = request.getParams();
        HashKey key = args[0].byteArray2hashKey();
        RedisOutputProtocol out = request.getOutputProtocol();
        out.writeArrayHeader(args.length - 1);
        Optional<GeoData> opt = request.getDatabase().get(key, GeoData.class);
        for (int i = 1; i < args.length; i++) {
            final HashKey memberKey = args[i].byteArray2hashKey();
            Optional<String> h = opt.flatMap(g -> g.geohash(memberKey));
            if (h.isPresent()) {
                out.writer(h.get().getBytes(StandardCharsets.UTF_8));
            } else {
                out.writerNull();
            }
        }
    }

    // -------------------------------------------------------------------------
    // GEOPOS key member [member ...]
    // -------------------------------------------------------------------------
    public void geopos(RedisRequest request) throws IOException {
        request.expectArgumentsCountGE(2);
        RequestParams[] args = request.getParams();
        HashKey key = args[0].byteArray2hashKey();
        RedisOutputProtocol out = request.getOutputProtocol();
        out.writeArrayHeader(args.length - 1);
        Optional<GeoData> opt = request.getDatabase().get(key, GeoData.class);
        for (int i = 1; i < args.length; i++) {
            final HashKey memberKey = args[i].byteArray2hashKey();
            Optional<double[]> pos = opt.flatMap(g -> g.getPosition(memberKey));
            if (pos.isPresent()) {
                double[] p = pos.get();
                out.writerMulti(
                        doubleToBytes(p[0]),
                        doubleToBytes(p[1]));
            } else {
                out.writerNull();
            }
        }
    }

    // -------------------------------------------------------------------------
    // GEORADIUS / GEORADIUS_RO
    // -------------------------------------------------------------------------
    public void georadius(RedisRequest request) throws IOException {
        georadiusCommon(request, false);
    }

    public void georadius_ro(RedisRequest request) throws IOException {
        georadiusCommon(request, true);
    }

    // -------------------------------------------------------------------------
    // GEORADIUSBYMEMBER / GEORADIUSBYMEMBER_RO
    // -------------------------------------------------------------------------
    public void georadiusbymember(RedisRequest request) throws IOException {
        georadiusByMemberCommon(request, false);
    }

    public void georadiusbymember_ro(RedisRequest request) throws IOException {
        georadiusByMemberCommon(request, true);
    }

    // -------------------------------------------------------------------------
    // Private: radius command implementation
    // -------------------------------------------------------------------------
    private void georadiusCommon(RedisRequest request, boolean readOnly) throws IOException {
        request.expectArgumentsCountGE(5);
        RequestParams[] args = request.getParams();
        HashKey key = args[0].byteArray2hashKey();
        double lon = args[1].byteArray2decimal().doubleValue();
        double lat = args[2].byteArray2decimal().doubleValue();
        double radiusM = GeoHashUtil.parseRadiusToMeters(args[3].byteArray2decimal().doubleValue(), args[4].getByteArray2string());
        String unit = args[4].getByteArray2string();
        RadiusOptions opts = RadiusOptions.parse(args, 5, readOnly);
        Optional<GeoData> opt = request.getDatabase().get(key, GeoData.class);
        if (!opt.isPresent()) {
            if (opts.storeKey != null) {
                request.getOutputProtocol().writer(0);
                return;
            }
            request.getOutputProtocol().writerMulti();
            return;
        }
        GeoData data = opt.get();
        List<GeoData.GeoMember> members = data.searchByRadius(lon, lat, radiusM,
                opts.withCoord, opts.withDist, opts.withHash, unit, opts.count, opts.asc);
        respondRadiusResult(request, members, opts, request.getDatabase(), readOnly);
    }

    private void georadiusByMemberCommon(RedisRequest request, boolean readOnly) throws IOException {
        request.expectArgumentsCountGE(4);
        RequestParams[] args = request.getParams();
        HashKey key = args[0].byteArray2hashKey();
        byte[] centerMember = args[1].getByteArray();
        double radiusM = GeoHashUtil.parseRadiusToMeters(args[2].byteArray2decimal().doubleValue(), args[3].getByteArray2string());
        String unit = args[3].getByteArray2string();
        RadiusOptions opts = RadiusOptions.parse(args, 4, readOnly);
        Optional<GeoData> opt = request.getDatabase().get(key, GeoData.class);
        if (!opt.isPresent()) {
            if (opts.storeKey != null) {
                request.getOutputProtocol().writer(0);
                return;
            }
            request.getOutputProtocol().writerMulti();
            return;
        }
        GeoData data = opt.get();
        List<GeoData.GeoMember> members = data.searchByMember(centerMember, radiusM,
                opts.withCoord, opts.withDist, opts.withHash, unit, opts.count, opts.asc);
        respondRadiusResult(request, members, opts, request.getDatabase(), readOnly);
    }

    private void respondRadiusResult(RedisRequest request, List<GeoData.GeoMember> members,
                                    RadiusOptions opts, RedisDatabase db, boolean readOnly) throws IOException {
        if (opts.storeKey != null && !readOnly) {
            storeGeoMembersAsZset(db, opts.storeKey, members, opts.storeDist);
            request.getOutputProtocol().writer(members.size());
            return;
        }
        writeGeoMembers(request, members);
    }

    private void writeGeoMembers(RedisRequest request, List<GeoData.GeoMember> members) throws IOException {
        RedisOutputProtocol out = request.getOutputProtocol();
        if (members.isEmpty()) {
            out.writerMulti();
            return;
        }
        out.writeArrayHeader(members.size());
        for (GeoData.GeoMember m : members) {
            List<Object> sub = new ArrayList<>(4);
            sub.add(m.getMember());
            if (m.isWithDist()) sub.add(doubleToBytes(m.getDist()));
            if (m.isWithHash()) sub.add(Long.valueOf(m.getHash()));
            if (m.isWithCoord()) {
                sub.add(doubleToBytes(m.getLon()));
                sub.add(doubleToBytes(m.getLat()));
            }
            out.writerComplex(sub.toArray());
        }
    }

    /** Store members into dest zset. scoreByDist: true = use distance as score, false = use geohash. */
    private void storeGeoMembersAsZset(RedisDatabase db, HashKey dest, List<GeoData.GeoMember> members, boolean scoreByDist) {
        SortedSetData zset = db.getOrCreate(dest, SortedSetData::new);
        if (!(zset instanceof SortedSetData)) return;
        for (GeoData.GeoMember m : members) {
            BigDecimal score = scoreByDist ? BigDecimal.valueOf(m.getDist()) : BigDecimal.valueOf(m.getHash());
            zset.sync(() -> zset.addOrReplace(new Member(m.getMember(), score)));
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------
    /** Returns GeoData for key, or null after writing WRONGTYPE. Creates key as GeoData if absent. */
    private GeoData getOrCreateGeoData(RedisRequest request, HashKey key) throws IOException {
        RedisDatabase db = request.getDatabase();
        Optional<com.github.microwww.redis.database.AbstractValueData<?>> existing = db.get(key);
        if (existing.isPresent()) {
            if (!(existing.get() instanceof GeoData)) {
                request.getOutputProtocol().writerError(RedisOutputProtocol.Level.ERR, WRONGTYPE_ERR);
                return null;
            }
            return (GeoData) existing.get();
        }
        return db.getOrCreate(key, GeoData::new);
    }

    private static byte[] doubleToBytes(double v) {
        return String.valueOf(v).getBytes(StandardCharsets.UTF_8);
    }

    /** Parsed options for GEORADIUS / GEORADIUSBYMEMBER. */
    private static final class RadiusOptions {
        final boolean withDist;
        final boolean withHash;
        final boolean withCoord;
        final int count;
        final boolean asc;
        /** Non-null if STORE or STOREDIST was given; storeDist is true only for STOREDIST. */
        final HashKey storeKey;
        final boolean storeDist;

        RadiusOptions(boolean withDist, boolean withHash, boolean withCoord, int count, boolean asc,
                      HashKey storeKey, boolean storeDist) {
            this.withDist = withDist;
            this.withHash = withHash;
            this.withCoord = withCoord;
            this.count = count;
            this.asc = asc;
            this.storeKey = storeKey;
            this.storeDist = storeDist;
        }

        static RadiusOptions parse(RequestParams[] args, int from, boolean readOnly) {
            boolean withDist = false, withHash = false, withCoord = false;
            int count = 0;
            boolean asc = true;
            HashKey storeKey = null;
            boolean storeDist = false;
            int i = from;
            while (i < args.length) {
                String opt = args[i].getByteArray2string().toUpperCase();
                switch (opt) {
                    case OPT_WITHDIST:
                        withDist = true;
                        i++;
                        break;
                    case OPT_WITHHASH:
                        withHash = true;
                        i++;
                        break;
                    case OPT_WITHCOORD:
                        withCoord = true;
                        i++;
                        break;
                    case OPT_COUNT:
                        if (i + 1 < args.length) {
                            count = args[++i].byteArray2int();
                            i++;
                        }
                        break;
                    case OPT_ASC:
                        asc = true;
                        i++;
                        break;
                    case OPT_DESC:
                        asc = false;
                        i++;
                        break;
                    case OPT_STORE:
                        if (!readOnly && i + 1 < args.length) {
                            storeKey = args[++i].byteArray2hashKey();
                            i++;
                        } else {
                            i++;
                        }
                        break;
                    case OPT_STOREDIST:
                        if (!readOnly && i + 1 < args.length) {
                            storeKey = args[++i].byteArray2hashKey();
                            storeDist = true;
                            i++;
                        } else {
                            i++;
                        }
                        break;
                    default:
                        i++;
                }
            }
            return new RadiusOptions(withDist, withHash, withCoord, count, asc, storeKey, storeDist);
        }
    }
}
