package com.github.microwww.redis.util;

/**
 * Geohash encoding/decoding and distance (Haversine). Generated by Cursor. Version: 0.3.4.
 */
public final class GeoHashUtil {

    private static final String BASE32 = "0123456789bcdefghjkmnpqrstuvwxyz";
    private static final double EARTH_RADIUS_M = 6_372_137;
    private static final double METERS_PER_KM = 1000;
    private static final double METERS_PER_MI = 1609.344;
    private static final double METERS_PER_FT = 0.3048;

    private GeoHashUtil() {
    }

    public static double parseRadiusToMeters(double value, String unit) {
        if (unit == null || unit.isEmpty()) {
            return value;
        }
        switch (unit.toLowerCase()) {
            case "m":
                return value;
            case "km":
                return value * METERS_PER_KM;
            case "mi":
                return value * METERS_PER_MI;
            case "ft":
                return value * METERS_PER_FT;
            default:
                return value;
        }
    }

    public static double formatDistance(double meters, String unit) {
        if (unit == null || "m".equalsIgnoreCase(unit)) {
            return meters;
        }
        switch (unit.toLowerCase()) {
            case "km":
                return meters / METERS_PER_KM;
            case "mi":
                return meters / METERS_PER_MI;
            case "ft":
                return meters / METERS_PER_FT;
            default:
                return meters;
        }
    }

    /**
     * Haversine distance in meters between two (lon, lat) points.
     */
    public static double distanceMeters(double lon1, double lat1, double lon2, double lat2) {
        double dLat = Math.toRadians(lat2 - lat1);
        double dLon = Math.toRadians(lon2 - lon1);
        double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                * Math.sin(dLon / 2) * Math.sin(dLon / 2);
        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        return EARTH_RADIUS_M * c;
    }

    /**
     * Encode (longitude, latitude) to base32 geohash string (precision 11 chars ~ 0.5m).
     */
    public static String encode(double longitude, double latitude) {
        return encode(longitude, latitude, 11);
    }

    public static String encode(double longitude, double latitude, int precision) {
        double[] lonRange = {-180.0, 180.0};
        double[] latRange = {-90.0, 90.0};
        StringBuilder hash = new StringBuilder();
        boolean isEven = true;
        int bit = 0;
        int ch = 0;

        while (hash.length() < precision) {
            if (isEven) {
                double mid = (lonRange[0] + lonRange[1]) / 2;
                if (longitude > mid) {
                    ch |= (1 << (4 - bit));
                    lonRange[0] = mid;
                } else {
                    lonRange[1] = mid;
                }
            } else {
                double mid = (latRange[0] + latRange[1]) / 2;
                if (latitude > mid) {
                    ch |= (1 << (4 - bit));
                    latRange[0] = mid;
                } else {
                    latRange[1] = mid;
                }
            }
            isEven = !isEven;
            bit++;
            if (bit == 5) {
                hash.append(BASE32.charAt(ch));
                bit = 0;
                ch = 0;
            }
        }
        return hash.toString();
    }

    /**
     * 52-bit style score for Redis compatibility (sortable). Not full Redis encoding.
     */
    public static long encode52Bit(double longitude, double latitude) {
        double[] lonRange = {-180.0, 180.0};
        double[] latRange = {-90.0, 90.0};
        long hash = 0;
        for (int i = 0; i < 26; i++) {
            double midLon = (lonRange[0] + lonRange[1]) / 2;
            hash <<= 1;
            if (longitude > midLon) {
                hash |= 1;
                lonRange[0] = midLon;
            } else {
                lonRange[1] = midLon;
            }
            double midLat = (latRange[0] + latRange[1]) / 2;
            hash <<= 1;
            if (latitude > midLat) {
                hash |= 1;
                latRange[0] = midLat;
            } else {
                latRange[1] = midLat;
            }
        }
        return hash;
    }
}
