package com.github.microwww.redis.database;

import com.github.microwww.redis.util.GeoHashUtil;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Geospatial index: member -> [longitude, latitude]. Redis stores GEO as zset; we use "zset" for getType(). Generated by Cursor. Version: 0.3.4.
 */
public class GeoData extends AbstractValueData<Map<HashKey, double[]>> implements DataLock {

    private final Map<HashKey, double[]> positions = new ConcurrentHashMap<>();

    public GeoData() {
        this(NEVER_EXPIRE);
    }

    public GeoData(int exp) {
        this.expire = exp;
        this.data = Collections.unmodifiableMap(positions);
    }

    @Override
    public String getType() {
        return "zset";
    }

    /**
     * @param nx only add if not exists
     * @param xx only update if exists
     * @return [addedCount, changedCount] when CH, else addedCount
     */
    public synchronized int[] add(boolean nx, boolean xx, boolean ch, double longitude, double latitude, byte[] member) {
        HashKey key = new HashKey(member);
        double[] prev = positions.get(key);
        int added = 0;
        int changed = 0;
        if (prev != null) {
            if (nx) {
                return ch ? new int[]{0, 0} : new int[]{0};
            }
            if (prev[0] != longitude || prev[1] != latitude) {
                changed = 1;
            }
        } else {
            if (xx) {
                return ch ? new int[]{0, 0} : new int[]{0};
            }
            added = 1;
        }
        positions.put(key, new double[]{longitude, latitude});
        version.incrementAndGet();
        if (ch) {
            return new int[]{added, changed};
        }
        return new int[]{added};
    }

    public Optional<double[]> getPosition(HashKey member) {
        return Optional.ofNullable(positions.get(member));
    }

    public Optional<double[]> getPosition(byte[] member) {
        return getPosition(new HashKey(member));
    }

    public Optional<Double> distance(HashKey m1, HashKey m2, String unit) {
        double[] p1 = positions.get(m1);
        double[] p2 = positions.get(m2);
        if (p1 == null || p2 == null) {
            return Optional.empty();
        }
        double m = GeoHashUtil.distanceMeters(p1[0], p1[1], p2[0], p2[1]);
        return Optional.of(GeoHashUtil.formatDistance(m, unit));
    }

    public Optional<String> geohash(HashKey member) {
        double[] p = positions.get(member);
        if (p == null) {
            return Optional.empty();
        }
        return Optional.of(GeoHashUtil.encode(p[0], p[1]));
    }

    public List<GeoMember> searchByRadius(double centerLon, double centerLat, double radiusMeters,
                                          boolean withCoord, boolean withDist, boolean withHash, String distUnit,
                                          int count, boolean asc) {
        List<GeoMember> list = new ArrayList<>();
        for (Map.Entry<HashKey, double[]> e : positions.entrySet()) {
            double[] pos = e.getValue();
            double d = GeoHashUtil.distanceMeters(centerLon, centerLat, pos[0], pos[1]);
            if (d <= radiusMeters) {
                double dist = distUnit != null ? GeoHashUtil.formatDistance(d, distUnit) : d;
                long hash = GeoHashUtil.encode52Bit(pos[0], pos[1]);
                list.add(new GeoMember(e.getKey().getBytes(), pos[0], pos[1], dist, hash, withCoord, withDist, withHash));
            }
        }
        list.sort(Comparator.comparingDouble(GeoMember::getDist));
        if (!asc) {
            Collections.reverse(list);
        }
        if (count > 0 && list.size() > count) {
            list = list.subList(0, count);
        }
        return list;
    }

    public List<GeoMember> searchByMember(byte[] member, double radiusMeters,
                                         boolean withCoord, boolean withDist, boolean withHash, String distUnit,
                                         int count, boolean asc) {
        double[] center = positions.get(new HashKey(member));
        if (center == null) {
            return Collections.emptyList();
        }
        return searchByRadius(center[0], center[1], radiusMeters, withCoord, withDist, withHash, distUnit, count, asc);
    }

    public int size() {
        return positions.size();
    }

    public static class GeoMember {
        private final byte[] member;
        private final double lon;
        private final double lat;
        private final double dist;
        private final long hash;
        private final boolean withCoord;
        private final boolean withDist;
        private final boolean withHash;

        GeoMember(byte[] member, double lon, double lat, double dist, long hash,
                  boolean withCoord, boolean withDist, boolean withHash) {
            this.member = member;
            this.lon = lon;
            this.lat = lat;
            this.dist = dist;
            this.hash = hash;
            this.withCoord = withCoord;
            this.withDist = withDist;
            this.withHash = withHash;
        }

        public byte[] getMember() {
            return member;
        }

        public double getDist() {
            return dist;
        }

        public long getHash() {
            return hash;
        }

        public boolean isWithCoord() {
            return withCoord;
        }

        public boolean isWithDist() {
            return withDist;
        }

        public boolean isWithHash() {
            return withHash;
        }

        public double getLon() {
            return lon;
        }

        public double getLat() {
            return lat;
        }
    }
}
