package com.github.microwww.redis.protocal.operation;

import com.github.microwww.AbstractRedisTest;
import org.junit.Test;
import redis.clients.jedis.GeoCoordinate;
import redis.clients.jedis.args.GeoUnit;
import redis.clients.jedis.params.GeoRadiusParam;
import redis.clients.jedis.resps.GeoRadiusResponse;

import java.util.List;
import java.util.HashMap;
import java.util.Map;
import redis.clients.jedis.params.GeoAddParams;

import static org.junit.Assert.*;

/**
 * Generated by Cursor. Version: 0.3.4.
 */
public class GeoOperationTest extends AbstractRedisTest {

    @Test
    public void testGeoaddAndGeopos() {
        String key = "geo:city" + Server.random(1)[0];
        long added = jedis.geoadd(key, 116.397128, 39.916527, "Beijing");
        assertEquals(1, added);
        added = jedis.geoadd(key, 121.472644, 31.231706, "Shanghai");
        assertEquals(1, added);
        List<GeoCoordinate> positions = jedis.geopos(key, "Beijing", "Shanghai", "NotFound");
        assertNotNull(positions);
        assertEquals(3, positions.size());
        assertNotNull(positions.get(0));
        assertEquals(116.397128, positions.get(0).getLongitude(), 1e-5);
        assertEquals(39.916527, positions.get(0).getLatitude(), 1e-5);
        assertNotNull(positions.get(1));
        assertNull(positions.get(2));
    }

    @Test
    public void testGeoaddAndNX() {
        String key = "geo:nx:" + Server.random(1)[0];
        Map<String, GeoCoordinate> coords = new HashMap<>();

        // 第一次使用 NX+CH 插入，不存在成员，应该新增 1 个并计为变更数，返回 1
        coords.put("city", new GeoCoordinate(10.0, 20.0));
        long changed = jedis.geoadd(key, GeoAddParams.geoAddParams().nx().ch(), coords);
        assertEquals(1, changed);

        // 第二次使用 NX+CH 插入同名成员但不同坐标，NX 不允许覆盖已有成员，返回 0
        coords.clear();
        coords.put("city", new GeoCoordinate(11.0, 21.0));
        changed = jedis.geoadd(key, GeoAddParams.geoAddParams().nx().ch(), coords);
        assertEquals(0, changed);

        // 校验最终坐标仍然是第一次插入的值
        List<GeoCoordinate> pos = jedis.geopos(key, "city");
        assertNotNull(pos);
        assertEquals(1, pos.size());
        assertNotNull(pos.get(0));
        assertEquals(10.0, pos.get(0).getLongitude(), 1e-5);
        assertEquals(20.0, pos.get(0).getLatitude(), 1e-5);
    }
    
    @Test
    public void testGeoaddAndXX() {
        String key = "geo:xx:" + Server.random(1)[0];
        Map<String, GeoCoordinate> coords = new HashMap<>();

        // 先正常插入一个点
        coords.put("city", new GeoCoordinate(10.0, 20.0));
        long changed = jedis.geoadd(key, coords);
        assertEquals(1, changed);

        // 使用 XX（不带 CH）：仅更新已存在元素，返回值是“新增数量”，因此更新坐标时返回 0
        coords.clear();
        coords.put("city", new GeoCoordinate(11.0, 21.0));
        changed = jedis.geoadd(key, GeoAddParams.geoAddParams().xx(), coords);
        assertEquals(0, changed);

        // 再次使用 XX+CH：这次更新应计入“变更数”，返回 1
        coords.clear();
        coords.put("city", new GeoCoordinate(12.0, 22.0));
        changed = jedis.geoadd(key, GeoAddParams.geoAddParams().xx().ch(), coords);
        assertEquals(1, changed);

        // 最终坐标应为最后一次更新后的值
        List<GeoCoordinate> pos = jedis.geopos(key, "city");
        assertNotNull(pos);
        assertEquals(1, pos.size());
        assertNotNull(pos.get(0));
        assertEquals(12.0, pos.get(0).getLongitude(), 1e-5);
        assertEquals(22.0, pos.get(0).getLatitude(), 1e-5);
    }

    @Test
    public void testGeodist() {
        String key = "geo:dist";
        jedis.geoadd(key, 0, 0, "origin");
        jedis.geoadd(key, 1, 0, "east");
        Double d = jedis.geodist(key, "origin", "east", GeoUnit.KM);
        assertNotNull(d);
        assertTrue(d > 100 && d < 120);
    }

    @Test
    public void testGeohash() {
        String key = "geo:hash";
        jedis.geoadd(key, 116.397128, 39.916527, "Beijing");
        List<String> hashes = jedis.geohash(key, "Beijing", "NotFound");
        assertNotNull(hashes);
        assertEquals(2, hashes.size());
        assertNotNull(hashes.get(0));
        assertTrue(hashes.get(0).length() >= 11);
        assertNull(hashes.get(1));
    }

    @Test
    public void testGeoradius() {
        String key = "geo:radius";
        jedis.geoadd(key, 116.397128, 39.916527, "Beijing");
        jedis.geoadd(key, 116.407526, 39.904030, "Tiananmen");
        jedis.geoadd(key, 121.472644, 31.231706, "Shanghai");
        List<GeoRadiusResponse> list = jedis.georadius(key, 116.4, 39.9, 50, GeoUnit.KM);
        assertNotNull(list);
        assertTrue(list.size() >= 2);
        list = jedis.georadius(key, 116.4, 39.9, 1, GeoUnit.KM, GeoRadiusParam.geoRadiusParam().count(1));
        assertNotNull(list);
        assertEquals(1, list.size());
    }

    @Test
    public void testGeoradiusByMember() {
        String key = "geo:bymember";
        jedis.geoadd(key, 116.397128, 39.916527, "Beijing");
        jedis.geoadd(key, 116.407526, 39.904030, "Tiananmen");
        List<GeoRadiusResponse> list = jedis.georadiusByMember(key, "Beijing", 50, GeoUnit.KM);
        assertNotNull(list);
        assertTrue(list.size() >= 2);
    }
}
